### ISSUE TITLE
Cmd + Click on urls to open them on browser

### ISSUE THREAD

**Issue by remorses** [janisdd/vscode-edit-csv#109]
### Version?
- vs code plugin

### Feature

Enable Cmd + Click on urls to open them on browser, like urls in terminal

**Comment by janisdd** [comment]
Interesting idea, I'll look into it.

Here are some initial thoughts (primarily for myself)

- is this possible in a webview? (probably, if not create a message to the extension process, different for desktop and browser versions)
- there is probably other text in the cell with the url
- url should be highlighted (e.g. underlined) before clicking (there is currently no way to format or change the content of a cell)
  - when the cell content gets converted into html (escaping!) other functions such as search, replace, ... have to operate on the real cell value not on the html (maybe this can be done with cell me
  - maybe `Cell Meta Data` can be used to store html/real value in combination with a custom cell renderer?

**Comment by janisdd** [comment]
I just experimented a bit with this and its easier (and probably more convenient) to show the link as a normal link in browser -> only click instead auf cmd+click

It will only support links starting with `http://` or `https://`

**Comment by janisdd** [comment]
As I tested more, cmd + click seems to in line with vs code and also enables easier editing of the cell.

mac: cmd + click
windows/linux: ctrl + click

cmd/ctrl + click are also used to select (multiple) individual cells but there is no other good solution...
One can click on the cell border to select the cell instead of opening the link.
