### ISSUE TITLE
Feature request: text wrap toggle

### ISSUE THREAD

**Issue by benlindsay** [janisdd/vscode-edit-csv#13]
Thanks for this plugin! It's fantastic and lets me avoid all the wonderful ways Excel f&*$s up my csvs. I notice that the extension now wraps text, which is nice to be able to do, but I'd also like to be able to turn that on or off. Additionally, if the wrapped text moves off screen, the line height can change, which can be a little jarring. Example below:

![csv-editor](https://user-images.githubusercontent.com/9361152/67152143-75fc5c80-f296-11e9-8c6f-5a72a689c5ed.gif)

I can see how in some cases this variable line height could be desirable, but when I'm trying to track a row while scrolling right and left, it's really hard when line heights keep jumping around. This problem would be solved for me though if I can just turn off all text wrapping so that all lines are the same height.

Thanks again!

**Comment by janisdd** [comment]
Hm by toggling do you mean a button in the ui? There is a vs code setting `csv-edit.enableWrapping` or something to permanently disable wrapping.

The jumping heigh is due to the virtual renderer which discard cells when they get too far out of the view port.. I can reproduce this in the latest (7.1.1) handsontable so this is by design(?)

What might also help a bit (when you just want to track one row) is to click on the row header which selects the whole row and gives an additional border.

**Comment by benlindsay** [comment]
Ooh, didn't see that option! While for my use case, being able to do word wrap and have fixed row heights would be nice, I'll get by just fine using that VS Code option, so I'll close this issue. Thanks again for this great tool!

**Comment by janisdd** [comment]
If you want to keep word wrap and there are only a few rows, you can manually resize the row heigh (at the top/bottom of the row heade) to something larger than the auto heigh. Then the manual heigh will be used und this should prevent the jumping ;)
