### ISSUE TITLE
How to keep the value model in a quotation mark ?

### ISSUE THREAD

**Issue by mrclemds** [janisdd/vscode-edit-csv#15]
I have some files containing different type of data like so:
```
"foo";"1";0;"2019-10-30";;
"bar";"2";0;"2019-10-30";;
```
And I would like to be able to configure this editor to keep my quotes _pattern_.

**Comment by janisdd** [comment]
Currently this is not possible because after the file is parsed by `papaparse` the quote-information is lost.
I can look into `papaparse` and check it's possible to extend/change the parser to keep the quote-information. However, there are some things that need to be considered:

- what about new cols? Should they be quoted?
- what about new rows
  - should cells in this row follow the column quote pattern?
  - what if cells in the same column are differently quoted (also for old rows)?

For new cols I would probably go with unquoted (and maybe an extension setting to change the default).

I'm not fully sure about the answers to these questions (and if there are other cases that should be considered). Without good answers (and explanations) we have undefined behaviour which I want to prevent.

**Comment by janisdd** [comment]
I think I got something working...

Currently the rules I use are:

- quote information is only stored for columns
- only the first non-comment, not empty row (no fields) is used to gather quote information
- if the first row has less cells than other rows
	- then missing entries are filled with `csv-edit.newColumnQuoteInformationIsQuoted` (default is not quoted)
- manually added columns will get `csv-edit.newColumnQuoteInformationIsQuoted` quote information
- moving columns will also "move" the quote information
	- e.g. column 3 was quoted and is now column 1 then column 1 is quoted after moving

Implications of this

- columns with mixed cells (quoted and not quoted fields) will get homogeneously quoted

Are you ok with that? Any suggestions?
