### ISSUE TITLE
Zoom support

### ISSUE THREAD

**Issue by jolsen-mitsu** [janisdd/vscode-edit-csv#155]
Please add the feature to to zoom in and out (with option to enable/disable this, if not everyone might like this functionality), similar to what's available in the VS Code editor when enabled. Control+Mousewheel is very convenient to quickly zoom in and out. Buttons/UI Controls and shortcut keys for zooming would also be nice. 

Thanks!

**Comment by janisdd** [comment]
Actually, this is not so easy because handsontable (used for rendering the table) does not support zoom: https://forum.handsontable.com/t/whenever-font-size-is-increased-cell-content-starts-overlapping/6290

I've been fiddling around a bit, and maybe it will work. However, a few questions come to mind:

- what should be zoomed? 
  - cell
  -  row headers
  - column headers
  - ui buttons
  - edit text (cell) editor
  - right click context menu
- sane min/max zoom
- granularity/steps for the zoom
  - there could be issues that make it necessary to have only XYZ predefined zoom levels

Again, I'm not sure whether this will work at all. Some features may depend on the fixed default cell height (22px), e.g. 
- auto row size
- auto column size
- cell content wrapping
- general (visual) overflow handing
- row virtualization

(these are just the ones I can think of, but there are many more features)

**Comment by janisdd** [comment]
After a few experiments, only the table cells (not the header rows) will be zoomed.
