### ISSUE TITLE
Request: compact view 

### ISSUE THREAD

**Issue by jolsen71** [janisdd/vscode-edit-csv#18]
This is a feature request. Please consider:
* adding UI setting for a "compact view" where the navigation elements and buttons at the top are smaller
* adding user settings where the font sizes/padding/margins can be tweaked (if not in settings UI, perhaps via editing CSS for power users)
* making the extension more responsive or relative to editor font size and VS Code zoom/scaling settings

I have small workspace and UI fonts selected, and I've also scaled VS Code down (ctrl+minus) so shrink the overall size of the editor and let me show more content on the screen at once. However, these changes doesn't seem to impact this extension's navigation row or buttons, or at least, not enough for me.

This is a screenshot that shows the font size in the Edit CSV tab navigation is almost twice as large as the tab and sidebar text. The command buttons are also large, but not as large, and even the font size in the table itself is larger than the text the rest of VS Code is using.

![image](https://user-images.githubusercontent.com/6641548/68916563-2a6d8f00-072c-11ea-9fb6-1ad464d10d78.png)

Thank you for the Edit CSV extension, your work is truly appreciated.

**Comment by janisdd** [comment]
>adding UI setting for a "compact view" where the navigation elements and buttons at the top are smaller

I checked and setting the font size will also shrink the elements (with some tweaking)

>making the extension more responsive or relative to editor font size and VS Code zoom/scaling settings

I think the editor zoom/scaling is working as intended (it just scales the whole view?)

>adding user settings where the font sizes/padding/margins can be tweaked (if not in settings UI, perhaps via editing CSS for power users)

Adding some font size option should work here...

By default the font size could sync with the editor font size.
With a setting one could overwrite this with an initial font size value.

But there is a problem/limitation with the row height... according to https://handsontable.com/docs/6.2.2/Options.html#rowHeights the row heigh should not be smaller than 23px.

**Comment by janisdd** [comment]
There is now an option `fontSizeInPx` which can be used to sync the font size with the editor or to choose specific font size
The ui elements now scale according to the font size

**Comment by jolsen-mitsu** [comment]
Thank you for looking into this. The buttons for Add row, add column, Tools, Help, etc., are still very large. I saw in another thread these are deliberately large for people on tablets with visual impairments. Would it be possible to make the size or maybe height configurable, so those of us who don't use this on a tablet or have visual issues can maximize our screen real estate while keeping the current view as the default?

I also noticed my grid size does not match my editor size, and I think it is because it is matching the font size, but not the zoom level, which makes them look different sizes if the zoom in the editor window is anything other than 100%. Please also keep in mind there are two zoom levels in VS Code, one for the entirety of VS Code (Ctrl+Plus and Ctrl+Minus) and also specific to the editor text (mouse wheel zoom). These are independent zoom settings.  The overall zoom VS Code setting does properly change effect the Edit CSV pane, but the pane does not match the zoom level of the related raw editor window, or allow its own independent zooming. 

Thanks again
