### ISSUE TITLE
large file support

### ISSUE THREAD

**Issue by dodjango** [janisdd/vscode-edit-csv#2]
Hi, my files are e.g. 15MB large, they cannot be viewed. The view opens but it keeps black and Nothing happens.

**Comment by janisdd** [comment]
Thx for the issue. I can reproduce this.
The first issue was that the initial size of the table was not set and the handsontable virtual renderer (renderAllRows) was not used (webview hangs).

1. After fixing this i noticed another issue: The background stays white (not the theme color).
I guess this is because the inline csv into html thing... the css `var(--vscode-editor-background)` is `""`

2. Anther small issue is the row header size for large files. For >=100 000 rows one can no longer see the actual row number (last digits are hidden).

To solve 1 i'll switch to postMessage to get the data to the webview after the webview is fully loaded.
(With this i could also introduce some progress bar showing how many csv data is already received. But the actual table rendering takes also some time...)

For 2 i need to search some more in the handsontable docs

The final update will take some time, probably some days (have not much time atm)

**Comment by dodjango** [comment]
I still see a White Background and no scroll bars when Opening my file:
![image](https://user-images.githubusercontent.com/8327172/56807886-54af3c00-6830-11e9-9dae-bd1f42106e68.png)
This file has about 13 MB and 31 columns.

**Comment by janisdd** [comment]
Do you se the status text `Rendering table...`/`Performing last steps...` next to the `Apply` button  when you open the csv editor?
When I installed the update (in a vm) it wasn't working first. After a vs code restart it was working... I guess a caching issue?
Can you please try some vs restarts and test again?
If this is not working try reinstalling the extension (which should definitely work).

**Comment by dodjango** [comment]
Thanks, now it works. VS Code asked me to reload after the update of the Extension but e full Restart was neccessary to enable your changes. Clicking around the table is still not very responsive but now it works and I can use it.

**Comment by janisdd** [comment]
Glad it works now. I can't do much about the performance thing (handsontable handles this) but I think it's ok-ish.
