### ISSUE TITLE
Custom quote character non respected

### ISSUE THREAD

**Issue by lrkwz** [janisdd/vscode-edit-csv#22]
There's something wrong here: data is quoted and escaped with `|` and columns are delimited by `;`

![image](https://user-images.githubusercontent.com/1025560/76086821-2b654d80-5fb5-11ea-8601-90737c2ba688.png)

**Comment by janisdd** [comment]
Hm I'm not really sure what you expect here...
Can you provide some example data and what the expected output is (preview I guess?)?

It's also helpful if you could write down the steps to reproduce this (including what options did you change etc.)

**Comment by lrkwz** [comment]
This can be an example file:

```csv
|Contatto|;|Email|;|Telefono1|;|Telefono2|;|Cognome e Nome|;|Codice Fiscale|;|P. Iva|;|Business|;|Indirizzo|;|Civico|;|CAP|;|Citta|;|Provincia|;|Tipo Documento|;|Cod. PV|;|ID Cassa|;|Numero vendita|;|Numero riga|;|Num Documento|;|Data acquisto|;|Cash|;|Assegno|;|Banca|;|Carta di Credito|;|Finanziaria|;|Bancomat|;|Non Riscossi|;|Resto|;|Fidelity|;|EAN Prodotto|;|Codice Prodotto|;|Descrizione Prodotto|;|Nr. di Serie|;|Tipo Vendita|;|Quantita|;|Prezzo|;|Regalo|;|Marchio|
|mario.rossi@example.com|;;;;;;;|N|;;;;;;|S|;|EURO10|;|1|;|2614|;|1|;|77|;|18/01/2020|;|0|;|0|;|0|;|164,88|;|0|;|0|;|0|;|0|;|2989017112303|;|3221614001154   |;|3422ASPR03985EA|;|RO3985/EA-  ASPIRAP.C/S TRAINO ROWENTA|;;|V|;|1|;|99,99|;|N|;|R O W E N T A|
|mario.rossi@example.com|;;;;;;;|N|;;;;;;|S|;|EURO10|;|1|;|2614|;|2|;|77|;|18/01/2020|;|0|;|0|;|0|;|164,88|;|0|;|0|;|0|;|0|;|2989017112303|;|8059617524944   |;|K22MCCKP123BKP|;|KP123BKP-NESCAFE DOLCE GUSTO KRUPS|;;|V|;|1|;|59,9|;|N|;|K R U P S|
```

data is quoted and escaped by `|` and columns are delimited by `;`  so I would expect to not see the `|` as happens if data is delimited by `"`.

**Comment by janisdd** [comment]
I think i got it now...so you think the displayed table is wrong? The cells should not contain the `|`?

If that is the issue then you need to click on `Reset data` button in the `Read options` because when you open the file the parser uses the initial read options (e.g. QuotChar: " and so on). When you change the read options you need to reset the data which will re-parse the content with the new options.

If you only edit files that use the same read options (different from the default ones) you can change the read option defaults in the plugin settings. Just search for `csv-edit read` and you can change them permanently.

**Comment by janisdd** [comment]
I assume this is solved
