### ISSUE TITLE
edit-csv broken UI on vscode insider

### ISSUE THREAD

**Issue by coffeehat** [janisdd/vscode-edit-csv#3]
# Bug description
Hello, I heavily rely on your extensions in daily work and very appreciate it.
Recently i turn to vscode insider version to use "Remote SSH" function
But on this version, edit-csv display an broken UI (as below) seems like failure of loading of CSS or js or whatelse
![image](https://user-images.githubusercontent.com/41894967/58218957-9a7df800-7d3b-11e9-9dcc-d0969c99e413.png)
I search the github, someone encounters the same issue: [Extension doesn't work with vscode-insider: Git Graph、Edit csv.](https://github.com/mhutchie/vscode-git-graph/issues/80). In that link the repo owner thinks it is caused by "fundamental change in how the JS & CSS are loaded (as they are stored on the remote system instead of the local machine)."

# How to reproduce
## Software version
* local os: Windows_NT x64 10.0.17763
* remote os: Ubuntu 16.04.1
* vscode: 1.35.0-insider (system setup)
* vscode extensions
    * Remote - SSH: 0.37.0
    * Edit csv: 0.0.11
## Steps
1. Install vscode insider and install Remote - SSH
2. Open an ubuntu remote machine using Remote - SSH
3. Install edit-csv, it will automatically installed on to the remote side
4. Create a new csv file on the remote, and use edit csv to display it

Then u can see the what i encountered.

I believe the os version is not correlated, under other os version the bug may also be reproduced.

## Notice
Sometimes on the first run after installation of insider, the edit-csv works well. But when u close and reopen the insider, the bug will emerge

**Comment by janisdd** [comment]
Thanks that you already searched for possible reasons :)
I'll look into that in the next few days (probably this weekend).

**Comment by janisdd** [comment]
I've tested a bit and I had no issues. I tested with macOS, windows 10 and remote was Ubuntu 18.04.2.

insider version was: 1.35.0 (2019-05-24)

Could you run a >Developer: Show Running Extensions and check if edit-csv is running remotely (has the `><` sign) or not?

I also tested with different setups where the plugin was
- installed locally and installed remotely,
- installed locally but not remotely (could not be used because not installed)
- not installed locally but remotely

they worked all.

![local-and-remote](https://user-images.githubusercontent.com/12775963/58371343-c2728480-7f10-11e9-8fdd-05726a140740.PNG)

The vs code insider download site states that they build daily, so it might be already fixed?

**Comment by coffeehat** [comment]
Thank's for the extensive test.
I update my insider version, then the issue disappear(*^_^*).

I should have told u the release date (Actually I didn't notice it)... The previous version caught issue is released at 2019-05-22T18:07:55.791Z. I run the command as u asked. It shows the edit-csv is running remotely but the UI is still broken. But after i update the insider, the issue all gone.

Maybe i should keep enough patience with a new-born software. Sorry about the time u cost
