### ISSUE TITLE
Manual file reload

### ISSUE THREAD

**Issue by mcjeikk** [janisdd/vscode-edit-csv#30]
Hello, Great work with this project, I enjoy it, but what about if create a button for reload the file, inside  of previewer?

**Comment by janisdd** [comment]
What do you mean by reload? Re-read the file content from the disk? Or reload the file content the moment you hit the `edit as csv`-button (this is already implemented in the read options -> Reset data and ...)?
Also note that both would need to discard all changes in the table.

**Comment by mcjeikk** [comment]
Hello, look, when there is any change in the viewer and it is saved, it works perfectly, only when I want to reload the file (another program may be editing it) I must close the viewer and click "edit as csv" again. What I mean is that it would be super cool to have a button within the same viewer that allows you to re-read the file from its modified source and view the updated content without having to close and reopen the file. When I click the reset data button it tells me that it is not going to re-read the file or reload the content of the scv but it is going to work with the content that is in memory and that content may be out of date.

**Comment by janisdd** [comment]
Ah ok, you want a real file reload from disk. I'm not fully sure how this should/would work properly.

When you hit reload:
- does the table has any changes? 
  - yes
    - display a warning dialog that changes will be discarded
  - no (e.g. nothing modified or changes were saved):
     - this should be fine

The only "problem" is that I don't fully trust the change detection.
And there are some other questions e.g. what about sorted columns or swapped/reordered columns?... I guess this must be discarded too

**Comment by janisdd** [comment]
The Feature is added now. I hope it is what you expected.

**Comment by mcjeikk** [comment]
Wow Nice work mate! is just what I sayed. Thank you

**Comment by janisdd** [comment]
Just for the docs, there is a small caveat... 
The way "reload file" is implemented is that the content of the vs code editor (`vscode.window.activeTextEditor`) is used.
The positive aspect is that this is automatically synced with file system changes without any additional effort.

When one "Apply changes to file" (without saving the file) the editor/table thinks there are no longer any changes (this is by design but could change in the future). Because `vscode.window.activeTextEditor` is used the reload gives the *unsaved* state of the file from vs code.

But consider this scenario:
- change table
- click "Apply changes to file" (without saving the changes/file)
- edit .csv file on disk with another program
- at this point reloading the file will reload the state of the file vs code thinks it is (when "Apply changes to file" was clicked)
  - because changes to the .csv file with another program will not be synced by vs code
  - it seems that when you save the file in vs code it detects the conflict and you can resolve it... after this the reload will work again as expected (is in sync with the file on disk)

I guess this behaviour is ok as it feels more "in line" with vscode and I doubt that another approach would be better.
