### ISSUE TITLE
Add setting for line ending characters

### ISSUE THREAD

**Issue by Elmegaard** [janisdd/vscode-edit-csv#34]
When I am updating our current .txt files, they are using another line ending convention than you use. Not sure what it is or what is setting it, but I assume it is your tool generating the "newlines", since after I click "edit csv" it is already showing changes in the file. When I hit save, many of the rows are edited already, causing conflicts in our git repository since not everyone wants to use this tool (yet).

Is it possible to set the line ending characters in the settings? It seems like it is adding some character '^M' after our rows, not entirely sure what it is. For now I'll have to use your tool to update the files, t hen copy the lines over to our code, which is a bit tedious.

**Comment by janisdd** [comment]
Normally the newline character from the input file is used (papaparse csv returns this). There currently only one reasons why you might see changes after hitting "edit csv":
- before displaying the data all rows are expanded so that they have the same length (cell count)

Newlines won't trigger the "unsaved changes indicator" (save icon),

Maybe you could provide some sample file?

**Comment by Elmegaard** [comment]
Well I read a bit more on it and it may be git doing it for me. Otherwise it is visual studio code setting it, I don't think it's your extension. Thank you though.
