### ISSUE TITLE
Rename header column in edit mode

### ISSUE THREAD

**Issue by mkloar** [janisdd/vscode-edit-csv#63]
### Version?
- VsCode plugin: 0.6.0

### Feature

I would like to have a feature where you can edit the header column (same option as 'Insert row above', 'Insert row below'...)

![image](https://user-images.githubusercontent.com/17946736/123263009-ceb6da80-d4f8-11eb-8f1b-d87dbbc77856.png)

The additional text says 'Edit' or double click will mark header column (input html element)...

**Comment by janisdd** [comment]
For small files this should be no problem as we can change the read options (`has header`), change the first line and change back the read options.

However, I see this can useful in some situations
- you scrolled in the csv (larger file) and then want to change the header
- we lose undo if we toggle the `has header` option

So I'll give it a try

**Comment by janisdd** [comment]
Will be part of the next update. Note that this is not a built-in function of handsontable so I had to create a workaround. This also means that for large tables editing the column header is relatively slow (100k rows takes ~2s).

Some caveats taken into account:
- undo/redo (is also slow in large files)
- horizontal scroll
- frequent scrolling (throttled)
- new value is applied on input blur/lose focus (cancel with `esc`)
- works with column reordering

The hard part was figuring out how to focus the input after the context menu disappeared because handsontable automatically tries to focus the table again after the context menu disappears. Also the column headers don't have a separate context menu (to know if a column header cell was clicked) so currently we check if all rows in a column are selected and only then display the edit header option.
