### ISSUE TITLE
Bug report: non-text-input key press interpreted as text-input

### ISSUE THREAD

**Issue by hmedina** [janisdd/vscode-edit-csv#64]
### What OS?
- Windows

### Version?
- both

### Description
Pressing non-input keys are interpreted as input keys, deleting a cell's contents.

### Steps to reproduce

1. have a CSV file opened, viewing the CSV edit tab,
2. select a cell that has content in it,
3. press the "launch calculator" key on the keyboard
-- > the cell's text is deleted, the caret appears on that cell, the calculator opens and takes focus away from Visual Studio Code

### More details

From https://keyboardchecker.com , the keys that trigger this behavior include:

- LaunchApplication2 (launch calculator key)
- AudioVolumeMute
- AudioVolumeUp
- AudioVolumeDown
- MediaPlayPause

Keyboard: Microsoft Ergonomic Keyboard 4000, V1
Behavior occurs with or without the Microsoft Keyboard and Mouse center installed.

**Comment by janisdd** [comment]
In fact my keyboard has none of these buttons so it's hard to test.
However, after some testing and looking through the handsontable code it might be expected behavior.

It's the same behavior as when you focus a cell and start to type. The only difference it that in your case no "new" character is inserted into the then empty cell.

I'm guessing you want to keep the cell content when you press these buttons?

There are two different ways this could be resolved:

- add special cases for these buttons (I would use the codes from https://www.freecodecamp.org/news/javascript-keycode-list-keypress-event-key-codes/). There might be some other special keys missing
- use handsontables´ method `isPrintableChar(keyCode)` which checks if the keyCode will produce a character. There might be some keys that are printable but not included in `isPrintableChar`

`isPrintableChar` is implemented as follows:

```js
function isPrintableChar(keyCode) {
  return keyCode === 32 || // space
  keyCode >= 48 && keyCode <= 57 || // 0-9
  keyCode >= 96 && keyCode <= 111 || // numpad
  keyCode >= 186 && keyCode <= 192 || // ;=,-./`
  keyCode >= 219 && keyCode <= 222 || // []{}\|"'
  keyCode >= 226 || // special chars (229 for Asian chars)
  keyCode >= 65 && keyCode <= 90; // a-z
}
```

To me approach 1 seems to be the better way as I have no idea if there are other keys (different languages) that would not be captured by `isPrintableChar`

**Comment by janisdd** [comment]
Implementation note: The involved handsontable class is `EditorManager`

**Comment by megapatato** [comment]
Yes, ideally I would like to keep the content when I press said buttons.

Is there a Visual Studio Code function you could use? In a regular text file, when double-clicking and selecting a word (i.e. anything flanked by `\w`), pressing a "text input" key will delete the selection, but pressing the "non-text input" keys does not, so VSC must have some function to filter out said inputs. I looked at the VSC API but I did not find something relevant (though I'm also not sure where it would even be...).

To add to the list of keys: Insert, ScrollLock, Pause/Break, and diacritics. When using the Windows English International keyboard map / layout (ENG-INTL) I observe the following:

Stock VSC workspace:
* select a word, press `'`, the selection remains
* select a word, press `'` + `e`, the selection is replaced with `é`

Edit CSV editor:
* select a cell, press `'`, the cell is cleared, but the cell is empty (text view shows two separators with nothing between them)
* select a cell, press `'` + `e`, the cell is cleared and `é` is inserted. 

Similar behavior with other diacritic marks, like `'` + `c` for `ç`, or `^` + `a` for `â`, and the tick mark ` for grave accents.

If the isPrintableChar function can swallow the Edit event if the keyCode is not printable, but will let "compound" keys pass through, that may be less maintenance and code-debt than trying to special case buttons.

**Comment by janisdd** [comment]
I'm not sure if "is not printable" is properly defined somewhere... (especially for more other languages like Chinese)

The "compound" is interesting, haven't thought about that. 

I will investigate this a bit more and also try to check how vs code does it.

**Comment by janisdd** [comment]
Diacritics should now work e.g. `^` will only clear the cell if you press another key (esc to cancel or click another cell) .

I've also added the special keys you mentioned... still not sure how to handle all keys (I'm afraid I might disable some keys from other keyboards).
